name: Code Review

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
      - "**.txt"

jobs:
  review:
    name: AI Code Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate AI Code Review
        uses: ./
        id: review
        continue-on-error: true
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          anthropic-key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "gpt-4-turbo-preview"
          api-to-use: "openai"
          include-full-files: "true"
          exclude-files: "package.json,go.sum,yarn.lock,*.lock"
          post-if-error: "true"
          style: "concise"
          persona: "developer"

      - name: Handle Review Failure
        if: steps.review.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const message = `⚠️ The AI code review failed to complete. Please check the workflow logs for details.`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: message
            });
